import { get, set } from "idb-keyval";
import { settings } from "../settings/settings";

/**
 * A workspace is a folder:
 *   deck.md       single source of truth
 *   images/       pasted / dropped images
 *   master.pptx   optional; auto-imported as the current master
 *   deck.json     written on export; consumed by tools/export_pptx.py
 *   out/deck.pptx generated by the export
 *
 * Two backends implement the same small interface:
 *   electron  - IPC to the main process (Node fs, chokidar watch, spawns the Python exporter)
 *   browser   - File System Access API (Chromium only), polling instead of watching
 */
export interface Backend {
  kind: "electron" | "browser";
  readText(rel: string): Promise<{ text: string; modified: number } | null>;
  readBlob(rel: string): Promise<Blob | null>;
  writeText(rel: string, text: string): Promise<number>;
  writeBlob(rel: string, blob: Blob): Promise<number>;
  modified(rel: string): Promise<number | null>;
  exists(rel: string): Promise<boolean>;
  /** Direct children (file names) of a folder; [] when it does not exist. */
  list(rel: string): Promise<string[]>;
  remove(rel: string): Promise<void>;
  /** Optional native file watching. Returns an unsubscribe. */
  watch?(cb: (rel: string) => void): Promise<() => void>;
  /** Optional: run the pptx exporter in place. */
  runExport?(deckJson: string, master: string, output: string): Promise<{ code: number; stdout: string; stderr: string }>;
  showItem?(rel: string): Promise<void>;
  /** Optional: pseudo-terminal bridge (desktop only). */
  pty?: {
    spawn(opts: { cwd: string; cols: number; rows: number }): Promise<number>;
    write(id: number, data: string): Promise<void>;
    resize(id: number, cols: number, rows: number): Promise<void>;
    kill(id: number): Promise<void>;
    onData(cb: (id: number, data: string) => void): () => void;
    onExit(cb: (id: number, code: number) => void): () => void;
  };
}

export interface Workspace {
  name: string;
  /** Absolute path when known (Electron). */
  path?: string;
  backend: Backend;
}

export const DECK_FILE = "deck.md";
export const MASTER_FILE = "master.pptx";
export const EXPORT_FILE = "deck.json";
export const OUTPUT_FILE = "out/deck.pptx";

export const isElectron = typeof window !== "undefined" && !!window.mdslide;
export const supportsWorkspace = isElectron || (typeof window !== "undefined" && "showDirectoryPicker" in window);

// ---------- Electron backend ----------

function electronBackend(root: string): Backend {
  const api = window.mdslide!;
  const abs = (rel: string) => `${root}/${rel}`;
  return {
    kind: "electron",
    readText: (rel) => api.readText(abs(rel)),
    readBlob: async (rel) => { const r = await api.readFile(abs(rel)); return r ? new Blob([r.data as BlobPart]) : null; },
    writeText: (rel, text) => api.writeText(abs(rel), text),
    writeBlob: async (rel, blob) => api.writeFile(abs(rel), new Uint8Array(await blob.arrayBuffer())),
    modified: (rel) => api.modified(abs(rel)),
    exists: (rel) => api.exists(abs(rel)),
    list: (rel) => api.list(abs(rel)),
    remove: (rel) => api.remove(abs(rel)),
    watch: async (cb) => { await api.watch(root); const off = api.onChanged(cb); return () => { off(); void api.unwatch(); }; },
    runExport: (deckJson, master, output) => api.runExport(root, abs(deckJson), abs(master), abs(output)),
    showItem: (rel) => api.showItem(abs(rel)),
    pty: { spawn: (o) => api.ptySpawn(o), write: (id, d) => api.ptyWrite(id, d), resize: (id, c, r) => api.ptyResize(id, c, r), kill: (id) => api.ptyKill(id), onData: (cb) => api.onPtyData(cb), onExit: (cb) => api.onPtyExit(cb) },
  };
}

// ---------- Browser backend (File System Access API) ----------

const HANDLE_KEY = "workspace:handle";

async function ensurePermission(handle: FileSystemDirectoryHandle): Promise<boolean> {
  if (typeof handle.queryPermission !== "function") return true; // e.g. OPFS handles
  if ((await handle.queryPermission({ mode: "readwrite" })) === "granted") return true;
  return (await handle.requestPermission({ mode: "readwrite" })) === "granted";
}

async function fileHandle(root: FileSystemDirectoryHandle, rel: string, create = false): Promise<FileSystemFileHandle> {
  const parts = rel.split("/").filter(Boolean);
  let dir = root;
  for (const p of parts.slice(0, -1)) dir = await dir.getDirectoryHandle(p, { create });
  return dir.getFileHandle(parts[parts.length - 1], { create });
}

function browserBackend(root: FileSystemDirectoryHandle): Backend {
  const write = async (rel: string, data: string | Blob) => {
    const h = await fileHandle(root, rel, true);
    const w = await h.createWritable();
    await w.write(data);
    await w.close();
    return (await h.getFile()).lastModified;
  };
  return {
    kind: "browser",
    readText: async (rel) => { try { const f = await (await fileHandle(root, rel)).getFile(); return { text: await f.text(), modified: f.lastModified }; } catch { return null; } },
    readBlob: async (rel) => { try { return await (await fileHandle(root, rel)).getFile(); } catch { return null; } },
    writeText: write,
    writeBlob: write,
    modified: async (rel) => { try { return (await (await fileHandle(root, rel)).getFile()).lastModified; } catch { return null; } },
    exists: async (rel) => { try { await fileHandle(root, rel); return true; } catch { return false; } },
    list: async (rel) => {
      try {
        let dir = root;
        for (const p of rel.split("/").filter(Boolean)) dir = await dir.getDirectoryHandle(p);
        const out: string[] = [];
        for await (const [name, h] of (dir as unknown as AsyncIterable<[string, { kind: string }]>)) if (h.kind === "file") out.push(name);
        return out;
      } catch { return []; }
    },
    remove: async (rel) => {
      const parts = rel.split("/").filter(Boolean);
      let dir = root;
      for (const p of parts.slice(0, -1)) dir = await dir.getDirectoryHandle(p);
      await dir.removeEntry(parts[parts.length - 1]);
    },
  };
}

// ---------- Opening ----------

export async function pickWorkspace(): Promise<Workspace | null> {
  if (isElectron) {
    const root = await window.mdslide!.openFolder();
    if (!root) return null;
    settings.update((v) => { v.workspace.lastPath = root; });
    return { name: root.split("/").pop() ?? root, path: root, backend: electronBackend(root) };
  }
  const root = await window.showDirectoryPicker({ mode: "readwrite" });
  await set(HANDLE_KEY, root);
  return { name: root.name, backend: browserBackend(root) };
}

/** Re-open the last workspace when possible. */
export async function restoreWorkspace(): Promise<Workspace | null> {
  if (isElectron) {
    const root = (await window.mdslide!.initialWorkspace()) ?? settings.get().workspace.lastPath;
    if (!root || !(await window.mdslide!.exists(root))) return null;
    settings.update((v) => { v.workspace.lastPath = root; });
    return { name: root.split("/").pop() ?? root, path: root, backend: electronBackend(root) };
  }
  const root = await get<FileSystemDirectoryHandle>(HANDLE_KEY);
  if (!root) return null;
  try { return (await ensurePermission(root)) ? { name: root.name, backend: browserBackend(root) } : null; } catch { return null; }
}

// ---------- Helpers used by the store ----------

export const readText = (ws: Workspace, rel: string) => ws.backend.readText(rel);
export const readBlob = (ws: Workspace, rel: string) => ws.backend.readBlob(rel);
export const writeText = (ws: Workspace, rel: string, text: string) => ws.backend.writeText(rel, text);
export const modifiedOf = (ws: Workspace, rel: string) => ws.backend.modified(rel);

/** Save an image under images/ with a unique name; returns the markdown-relative path. */
export async function saveImage(ws: Workspace, blob: Blob, baseName: string): Promise<string> {
  const ext = blob.type === "image/jpeg" ? "jpg" : blob.type === "image/gif" ? "gif" : blob.type === "image/svg+xml" ? "svg" : "png";
  const base = sanitize(baseName) || "image";
  let name = `${base}.${ext}`;
  for (let i = 2; await ws.backend.exists(`images/${name}`); i++) name = `${base}-${i}.${ext}`;
  await ws.backend.writeBlob(`images/${name}`, blob);
  return `images/${name}`;
}

/** Resolve a markdown-relative image path to an object URL. */
export async function imageUrl(ws: Workspace, relPath: string): Promise<string | null> {
  const blob = await ws.backend.readBlob(relPath);
  return blob ? URL.createObjectURL(blob) : null;
}

/** File-name safe: keep Japanese, letters, digits; replace the rest with "-". */
export function sanitize(s: string): string {
  return s.replace(/[\\/:*?"<>|\s.()（）{}\[\]]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40);
}

// Minimal typings for the File System Access API (not in TS DOM lib for all versions).
declare global {
  interface Window { showDirectoryPicker(options?: { mode?: "read" | "readwrite" }): Promise<FileSystemDirectoryHandle> }
  interface FileSystemDirectoryHandle {
    queryPermission(d: { mode: "read" | "readwrite" }): Promise<PermissionState>;
    requestPermission(d: { mode: "read" | "readwrite" }): Promise<PermissionState>;
  }
}
