import { get, set } from "idb-keyval";
import { settings } from "../settings/settings";

/**
 * A workspace is a folder, entered through the Markdown file inside it:
 *   <deckFile>    single source of truth (default deck.md; any name when opened as a file)
 *   images/       pasted / dropped images
 *   master.pptx   optional; auto-imported as the current master
 *   deck.json     written on export; consumed by tools/export_pptx.py
 *   out/deck.pptx generated by the export
 *
 * Two backends implement the same small interface:
 *   electron  - IPC to the main process (Node fs, chokidar watch, spawns the Python exporter)
 *   browser   - File System Access API (Chromium only), polling instead of watching
 */
export interface Backend {
  kind: "electron" | "browser";
  readText(rel: string): Promise<{ text: string; modified: number } | null>;
  readBlob(rel: string): Promise<Blob | null>;
  writeText(rel: string, text: string): Promise<number>;
  writeBlob(rel: string, blob: Blob): Promise<number>;
  modified(rel: string): Promise<number | null>;
  exists(rel: string): Promise<boolean>;
  /** Direct children (file names) of a folder; [] when it does not exist. */
  list(rel: string): Promise<string[]>;
  remove(rel: string): Promise<void>;
  /** Optional native file watching. Returns an unsubscribe. */
  watch?(cb: (rel: string) => void): Promise<() => void>;
  /** Optional: run the pptx exporter in place. `master` is folder-relative, or absolute when it comes from the masters folder. */
  runExport?(deckJson: string, master: string, output: string): Promise<{ code: number; stdout: string; stderr: string }>;
  showItem?(rel: string): Promise<void>;
  /** Optional: pseudo-terminal bridge (desktop only). */
  pty?: {
    spawn(opts: { cwd: string; cols: number; rows: number }): Promise<number>;
    write(id: number, data: string): Promise<void>;
    resize(id: number, cols: number, rows: number): Promise<void>;
    kill(id: number): Promise<void>;
    onData(cb: (id: number, data: string) => void): () => void;
    onExit(cb: (id: number, code: number) => void): () => void;
  };
}

export interface Workspace {
  name: string;
  /** Absolute path when known (Electron). */
  path?: string;
  /** The deck's Markdown file, relative to the folder (default deck.md). */
  deckFile: string;
  backend: Backend;
}

export const DECK_FILE = "deck.md";
export const MASTER_FILE = "master.pptx";
export const EXPORT_FILE = "deck.json";
export const OUTPUT_FILE = "out/deck.pptx";

export const isElectron = typeof window !== "undefined" && !!window.mdslide;
export const supportsWorkspace = isElectron || (typeof window !== "undefined" && "showDirectoryPicker" in window);

// ---------- Electron backend ----------

function electronBackend(root: string): Backend {
  const api = window.mdslide!;
  const abs = (rel: string) => `${root}/${rel}`;
  return {
    kind: "electron",
    readText: (rel) => api.readText(abs(rel)),
    readBlob: async (rel) => { const r = await api.readFile(abs(rel)); return r ? new Blob([r.data as BlobPart]) : null; },
    writeText: (rel, text) => api.writeText(abs(rel), text),
    writeBlob: async (rel, blob) => api.writeFile(abs(rel), new Uint8Array(await blob.arrayBuffer())),
    modified: (rel) => api.modified(abs(rel)),
    exists: (rel) => api.exists(abs(rel)),
    list: (rel) => api.list(abs(rel)),
    remove: (rel) => api.remove(abs(rel)),
    watch: async (cb) => { await api.watch(root); const off = api.onChanged(cb); return () => { off(); void api.unwatch(); }; },
    runExport: (deckJson, master, output) => api.runExport(root, abs(deckJson), master.startsWith("/") ? master : abs(master), abs(output)),
    showItem: (rel) => api.showItem(abs(rel)),
    pty: { spawn: (o) => api.ptySpawn(o), write: (id, d) => api.ptyWrite(id, d), resize: (id, c, r) => api.ptyResize(id, c, r), kill: (id) => api.ptyKill(id), onData: (cb) => api.onPtyData(cb), onExit: (cb) => api.onPtyExit(cb) },
  };
}

// ---------- Browser backend (File System Access API) ----------

const HANDLE_KEY = "workspace:handle";

async function ensurePermission(handle: FileSystemDirectoryHandle): Promise<boolean> {
  if (typeof handle.queryPermission !== "function") return true; // e.g. OPFS handles
  if ((await handle.queryPermission({ mode: "readwrite" })) === "granted") return true;
  return (await handle.requestPermission({ mode: "readwrite" })) === "granted";
}

async function fileHandle(root: FileSystemDirectoryHandle, rel: string, create = false): Promise<FileSystemFileHandle> {
  const parts = rel.split("/").filter(Boolean);
  let dir = root;
  for (const p of parts.slice(0, -1)) dir = await dir.getDirectoryHandle(p, { create });
  return dir.getFileHandle(parts[parts.length - 1], { create });
}

function browserBackend(root: FileSystemDirectoryHandle): Backend {
  const write = async (rel: string, data: string | Blob) => {
    const h = await fileHandle(root, rel, true);
    const w = await h.createWritable();
    await w.write(data);
    await w.close();
    return (await h.getFile()).lastModified;
  };
  return {
    kind: "browser",
    readText: async (rel) => { try { const f = await (await fileHandle(root, rel)).getFile(); return { text: await f.text(), modified: f.lastModified }; } catch { return null; } },
    readBlob: async (rel) => { try { return await (await fileHandle(root, rel)).getFile(); } catch { return null; } },
    writeText: write,
    writeBlob: write,
    modified: async (rel) => { try { return (await (await fileHandle(root, rel)).getFile()).lastModified; } catch { return null; } },
    exists: async (rel) => { try { await fileHandle(root, rel); return true; } catch { return false; } },
    list: async (rel) => {
      try {
        let dir = root;
        for (const p of rel.split("/").filter(Boolean)) dir = await dir.getDirectoryHandle(p);
        const out: string[] = [];
        for await (const [name, h] of (dir as unknown as AsyncIterable<[string, { kind: string }]>)) if (h.kind === "file") out.push(name);
        return out;
      } catch { return []; }
    },
    remove: async (rel) => {
      const parts = rel.split("/").filter(Boolean);
      let dir = root;
      for (const p of parts.slice(0, -1)) dir = await dir.getDirectoryHandle(p);
      await dir.removeEntry(parts[parts.length - 1]);
    },
  };
}

// ---------- Opening ----------

export interface RecentEntry { path: string; deckFile: string }

/** Remember the document for the next start and the start screen's recent list (most recent first, 8 entries). */
function remember(root: string, deckFile: string) {
  settings.update((v) => {
    v.workspace.lastPath = root;
    v.workspace.lastDeckFile = deckFile;
    v.workspace.recent = [{ path: root, deckFile }, ...v.workspace.recent.filter((r) => !(r.path === root && r.deckFile === deckFile))].slice(0, 8);
  });
}

function electronWorkspace(root: string, deckFile: string): Workspace {
  return { name: root.split("/").pop() ?? root, path: root, deckFile, backend: electronBackend(root) };
}

/** "/a/b/c.md" -> folder "/a/b" and file "c.md". */
function splitFile(file: string): { root: string; deckFile: string } {
  const i = Math.max(file.lastIndexOf("/"), file.lastIndexOf("\\"));
  return { root: file.slice(0, i), deckFile: file.slice(i + 1) };
}

/** Open a folder; the deck is deck.md inside it (scaffolded on first load when missing). */
export async function pickWorkspace(): Promise<Workspace | null> {
  if (isElectron) {
    const root = await window.mdslide!.openFolder({ title: "資料のフォルダを開く", buttonLabel: "開く" });
    if (!root) return null;
    remember(root, DECK_FILE);
    return electronWorkspace(root, DECK_FILE);
  }
  const root = await window.showDirectoryPicker({ mode: "readwrite" });
  await set(HANDLE_KEY, root);
  return { name: root.name, deckFile: DECK_FILE, backend: browserBackend(root) };
}

/** Desktop: choose a Markdown file. Its folder becomes the workspace and the file keeps its name. */
export async function openMarkdownFile(): Promise<Workspace | null> {
  if (!isElectron) return null;
  const file = await window.mdslide!.openMarkdown();
  if (!file) return null;
  const { root, deckFile } = splitFile(file);
  remember(root, deckFile);
  return electronWorkspace(root, deckFile);
}

/**
 * Desktop: choose (or create, in the dialog) the folder for a new deck. The deck is deck.md inside it; the store scaffolds
 * it on load when it does not exist yet. A folder, not a file: images/, notes/ and the master live next to the Markdown.
 */
export async function createWorkspaceFolder(): Promise<Workspace | null> {
  if (!isElectron) return null;
  const root = await window.mdslide!.openFolder({ title: "新しい資料のフォルダ", buttonLabel: "ここに作る", message: `資料ごとに 1 フォルダ。${DECK_FILE} と images/ がこの中にできます。新しいフォルダを作って選んでもかまいません。` });
  if (!root) return null;
  remember(root, DECK_FILE);
  return electronWorkspace(root, DECK_FILE);
}

/** Desktop: an entry of the recent list; null when its file has gone. */
export async function openRecentWorkspace(entry: RecentEntry): Promise<Workspace | null> {
  if (!isElectron || !(await window.mdslide!.exists(`${entry.path}/${entry.deckFile}`))) return null;
  remember(entry.path, entry.deckFile);
  return electronWorkspace(entry.path, entry.deckFile);
}

/**
 * Re-open the last document when possible. A folder or .md file given on the command line wins (and may scaffold the deck);
 * the remembered document is restored only while its file still exists, otherwise the start screen shows.
 */
export async function restoreWorkspace(): Promise<Workspace | null> {
  if (isElectron) {
    const api = window.mdslide!;
    const initial = await api.initialWorkspace();
    if (initial) {
      if (!(await api.exists(initial.root))) return null;
      const deckFile = initial.deckFile ?? DECK_FILE;
      remember(initial.root, deckFile);
      return electronWorkspace(initial.root, deckFile);
    }
    const { lastPath, lastDeckFile } = settings.get().workspace;
    if (!lastPath) return null;
    const deckFile = lastDeckFile ?? DECK_FILE;
    if (!(await api.exists(`${lastPath}/${deckFile}`))) return null;
    return electronWorkspace(lastPath, deckFile);
  }
  const root = await get<FileSystemDirectoryHandle>(HANDLE_KEY);
  if (!root) return null;
  try { return (await ensurePermission(root)) ? { name: root.name, deckFile: DECK_FILE, backend: browserBackend(root) } : null; } catch { return null; }
}

// ---------- Helpers used by the store ----------

export const readText = (ws: Workspace, rel: string) => ws.backend.readText(rel);
export const readBlob = (ws: Workspace, rel: string) => ws.backend.readBlob(rel);
export const writeText = (ws: Workspace, rel: string, text: string) => ws.backend.writeText(rel, text);
export const modifiedOf = (ws: Workspace, rel: string) => ws.backend.modified(rel);

/** Save an image under images/ with a unique name; returns the markdown-relative path. */
export async function saveImage(ws: Workspace, blob: Blob, baseName: string): Promise<string> {
  const ext = blob.type === "image/jpeg" ? "jpg" : blob.type === "image/gif" ? "gif" : blob.type === "image/svg+xml" ? "svg" : "png";
  const base = sanitize(baseName) || "image";
  let name = `${base}.${ext}`;
  for (let i = 2; await ws.backend.exists(`images/${name}`); i++) name = `${base}-${i}.${ext}`;
  await ws.backend.writeBlob(`images/${name}`, blob);
  return `images/${name}`;
}

/** Resolve a markdown-relative image path to an object URL. */
export async function imageUrl(ws: Workspace, relPath: string): Promise<string | null> {
  const blob = await ws.backend.readBlob(relPath);
  return blob ? URL.createObjectURL(blob) : null;
}

/** File-name safe: keep Japanese, letters, digits; replace the rest with "-". */
export function sanitize(s: string): string {
  return s.replace(/[\\/:*?"<>|\s.()（）{}\[\]]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40);
}

// Minimal typings for the File System Access API (not in TS DOM lib for all versions).
declare global {
  interface Window { showDirectoryPicker(options?: { mode?: "read" | "readwrite" }): Promise<FileSystemDirectoryHandle> }
  interface FileSystemDirectoryHandle {
    queryPermission(d: { mode: "read" | "readwrite" }): Promise<PermissionState>;
    requestPermission(d: { mode: "read" | "readwrite" }): Promise<PermissionState>;
  }
}
